apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-mottak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8090
  leaderElection: true
  liveness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "2"
    requests:
      memory: 1024Mi
      cpu: 200m
  ingresses:
    - https://familie-ba-mottak.dev-fss-pub.nais.io
    - https://familie-ba-mottak.dev.adeo.no
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
