application:
  name: familie-ba-mottak

server:
  servlet:
    context-path: /
  port: 8090
spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  kafka:
    client-id: familie-ba-mottak
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CREDENTIAL_USERNAME}" password="${CREDENTIAL_PASSWORD}";
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: srvfamilie-ba-mottak
      max-poll-records: 1
      auto-offset-reset: none
      enable-auto-commit: false
  datasource:
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
  flyway:
    enabled: true
  http:
    encoding:
      charset: UTF-8

logging:
  config: "classpath:logback-spring.xml"

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    cluster: ${NAIS_CLUSTER_NAME}
    applicationName: ${NAIS_APP_NAME}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true
  health:
    db:
      enabled: true

FAMILIE_BA_DOKGEN_API_URL: http://familie-ba-dokgen
FAMILIE_INTEGRASJONER_API_URL: http://familie-integrasjoner/api
FAMILIE_BA_SAK_API_URL: http://familie-ba-sak/api
FAMILIE_BA_INFOTRYGD_BARNETRYGD_API_URL: http://infotrygd-barnetrygd
ACCEPTEDAUDIENCE: dummy
