no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${MOTTAK_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      ba-sak-clientcredentials:
        resource-url: ${FAMILIE_BA_SAK_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${MOTTAK_BA_SAK_SCOPE}
        authentication:
          client-id: ${MOTTAK_CLIENT_ID}
          client-secret: ${MOTTAK_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${MOTTAK_FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${MOTTAK_CLIENT_ID}
          client-secret: ${MOTTAK_CLIENT_SECRET}
          client-auth-method: client_secret_basic


spring:
  cloud:
    vault:
      database:
        role: familie
  datasource:
    url: jdbc:postgresql://postgres-mottak:5432/familiebamottak
    hikari:
      username: familie
      password: familie-pwd
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
      schema.registry.url: http://schema-registry:8081
    consumer:
      group-id: srvc01
funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://dummy/api/
    cluster: localhost
    applicationName: familie-ba-sak

logging:
  level:
    org: INFO
    no.nav: DEBUG
#  config: "classpath:logback-test.xml"

FAMILIE_BA_SAK_API_URL: http://familie-ba-sak:8089/api
FAMILIE_INTEGRASJONER_API_URL: http://familie-integrasjoner:8085/api

FØDSELSHENDELSE_VENT_PÅ_TPS_MINUTTER: 1
FØDSELSHENDELSE_REKJØRINGSINTERVALL_MINUTTER: 1

KAFKA_BROKERS: http://kafka:9093
